# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DATKLL/constraint.xdc

# Block Designs: bd/clock_wizard/clock_wizard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard || ORIG_REF_NAME==clock_wizard} -quiet] -quiet

# IP: bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clock_wizard_clk_wiz_0_0 || ORIG_REF_NAME==clock_wizard_clk_wiz_0_0} -quiet] -quiet

# XDC: c:/Users/tuankiet/Desktop/RISCV-with-UART/RISCV-with-UART.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_wizard_clk_wiz_0_0 || ORIG_REF_NAME==clock_wizard_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/tuankiet/Desktop/RISCV-with-UART/RISCV-with-UART.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clock_wizard_clk_wiz_0_0 || ORIG_REF_NAME==clock_wizard_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/tuankiet/Desktop/RISCV-with-UART/RISCV-with-UART.gen/sources_1/bd/clock_wizard/ip/clock_wizard_clk_wiz_0_0/clock_wizard_clk_wiz_0_0_ooc.xdc

# XDC: c:/Users/tuankiet/Desktop/RISCV-with-UART/RISCV-with-UART.gen/sources_1/bd/clock_wizard/clock_wizard_ooc.xdc
